### ISSUE TITLE
ModuleNotFoundError: No module named 'AlignDet'

### ISSUE THREAD

**Issue by hit-lyw** [mitming/AlignDet#22]
`raceback (most recent call last):
  File "D:\miniconda\envs\my_aligndet\lib\site-packages\mmcv\utils\misc.py", line 73, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "D:\miniconda\envs\my_aligndet\lib\importlib\__init__.py", line 127, in import_module 
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'AlignDet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\lyw\lyw_weed\AlignDet\tools\train.py", line 242, in <module>
    main()
    cfg = Config.fromfile(args.config)
  File "D:\miniconda\envs\my_aligndet\lib\site-packages\mmcv\utils\config.py", line 343, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "D:\miniconda\envs\my_aligndet\lib\site-packages\mmcv\utils\misc.py", line 80, in import_modules_from_strings
    raise ImportError
ImportError`

**Comment by hit-lyw** [comment]
Hi I am getting the above error while running the pre-training code, what is the reason for this?

**Comment by liming-ai** [comment]
> Hi I am getting the above error while running the pre-training code, what is the reason for this?

I run it on Linux system without any problem, please try it on Linux and make sure all environment is configured correctly, thank you

**Comment by hit-lyw** [comment]
好的谢谢，我加入sys.path.append(项目的根目录后得到解决)




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ming ***@***.***&gt;; 
发送时间: 2024年1月1日(星期一) 上午9:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liming-ai/AlignDet] ModuleNotFoundError: No module named &#39;AlignDet&#39; (Issue #22)






嗨，我得到上面的错误，而运行前培训代码，这是什么原因？

我在Linux系统上运行它没有任何问题，请尝试在Linux上，并确保所有的环境配置正确，谢谢

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
您收到此消息是因为您创建了线程。消息ID:< minim - ai / AlignDet /议题/ 22 / ***@***.***和&gt;

**Comment by liming-ai** [comment]
> 好的谢谢，我加入sys.path.append(项目的根目录后得到解决)
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Ming ***@***.***&gt;; 发送时间: 2024年1月1日(星期一) 上午9:22 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [liming-ai/AlignDet] ModuleNotFoundError: No module named &#39;AlignDet&#39; (Issue #22) 嗨，我得到上面的错误，而运行前培训代码，这是什么原因？ 我在Linux系统上运行它没有任何问题，请尝试在Linux上，并确保所有的环境配置正确，谢谢 - 直接回复这封邮件，在GitHub上查看，或取消订阅. 您收到此消息是因为您创建了线程。消息ID:< minim - ai / AlignDet /议题/ 22 / ***@***.***和&gt;

Thank you for your interest and reply. Happy New Year.

**Comment by FancyChen085** [comment]
> 好的谢谢，我加入sys.path.append(项目的根目录后得到解决)
> […](#)

请问您是在哪个文件中加入这段代码的，我尝试在train.py 文件中加入sys.path.append("./AlignDet")但是没有效果
